# Stubs for flask_sqlalchemy._compat (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

PY2: Any

def iteritems(d: Any): ...
def itervalues(d: Any): ...
xrange = xrange
string_types: Any

def to_str(x: Any, charset: str = ..., errors: str = ...): ...
xrange = range
